print("Hello world")
print("You must be the legendary god that comes from the sky")
print("We have been waiting for for a long time")
print("Our legend says you will be very tasty with the mustard")
print("We will have a feast tonight unless you say")